AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    ads-api

    Sample SAM Template for ads-api

Globals:
    Function:
        Timeout: 60

        LoggingConfig:
            LogFormat: JSON
        Environment:
            Variables:
                Env: !Ref Env
                AdsTableName: !Ref AdsTableName
                AdsBucketName: !Sub '${AppCode}-${Env}-bucket-${AWS::AccountId}'
                AdsTopicName: !Ref AdsTopicName
                AdsTopicArn: !Ref AdsTopic
    Api:
        Auth:
            Authorizers:
                CognitoAuthorizer:
                    UserPoolArn: !GetAtt UserPool.Arn

Parameters:
    Env:
        Type: String
        Default: dev
    AdsTableName:
        Type: String
        Default: AdsTable-dev
    AppCode:
        Type: String
        Default: ads-api
    AdsTopicName:
        Type: String
        Default: ads-api-dev-notifications

Resources:
    # Lambda
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub '${AppCode}-${Env}-hello-world'
            CodeUri: src/functions/hello-world/
            Handler: handler.lambdaHandler
            Runtime: nodejs22.x
            Architectures:
                - x86_64
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /hello
                        Method: get
                        Auth:
                            Authorizer: CognitoAuthorizer

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - handler.ts
    AdsFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub '${AppCode}-${Env}-create-ad'
            CodeUri: src/functions/ads/
            Handler: handler.lambdaHandler
            Role: !GetAtt AdsFunctionRole.Arn
            Runtime: nodejs22.x
            Architectures:
                - x86_64
            Events:
                CreateAdApi:
                    Type: Api
                    Properties:
                        Path: /ads
                        Method: post
                        Auth:
                            Authorizer: CognitoAuthorizer
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: es2020
                Sourcemap: true
                EntryPoints:
                    - handler.ts

    # DynamoDB
    AdsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Ref AdsTableName
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST

    # S3 Bucket
    AdsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub '${AppCode}-${Env}-bucket-${AWS::AccountId}'

    # SNS Topic
    AdsTopic:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: !Ref AdsTopicName

    # Cognito User Pool
    UserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: !Sub '${AppCode}-${Env}-user-pool'
            AutoVerifiedAttributes:
                - email
            UsernameAttributes:
                - email
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireUppercase: true
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: false
            Schema:
                - Name: email
                  AttributeDataType: String
                  Required: true
                  Mutable: false

    UserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: !Sub '${AppCode}-${Env}-user-pool-client'
            UserPoolId: !Ref UserPool
            GenerateSecret: false
            ExplicitAuthFlows:
                - ALLOW_USER_PASSWORD_AUTH
                - ALLOW_REFRESH_TOKEN_AUTH
                - ALLOW_USER_SRP_AUTH

    # IAM Role
    AdsFunctionRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub '${AppCode}-${Env}-ads-function-role'
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            Policies:
                - PolicyName: DynamoDBAccess
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - dynamodb:PutItem
                                - dynamodb:GetItem
                                - dynamodb:UpdateItem
                                - dynamodb:DeleteItem
                                - dynamodb:Query
                                - dynamodb:Scan
                            Resource: !GetAtt AdsTable.Arn
                - PolicyName: S3Access
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:PutObject
                                - s3:GetObject
                                - s3:DeleteObject
                            Resource: !Sub '${AdsBucket.Arn}/*'
                - PolicyName: SNSPublishAccess
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - sns:Publish
                            Resource: !Ref AdsTopic

Outputs:
    HelloWorldApi:
        Description: API Gateway endpoint URL for Prod stage for Hello World function
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    HelloWorldFunction:
        Description: Hello World Lambda Function ARN
        Value: !GetAtt HelloWorldFunction.Arn
    HelloWorldFunctionIamRole:
        Description: Implicit IAM Role created for Hello World function
        Value: !GetAtt HelloWorldFunctionRole.Arn
    UserPoolId:
        Description: Cognito User Pool ID
        Value: !Ref UserPool
    UserPoolClientId:
        Description: Cognito User Pool Client ID
        Value: !Ref UserPoolClient
    UserPoolArn:
        Description: Cognito User Pool ARN
        Value: !GetAtt UserPool.Arn
